addEventListener('load',()=>setTimeout(()=>document.querySelector('#loader').classList.add('hide'),700));
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.go).scrollIntoView({behavior:'smooth'}));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.grid figure').forEach(x=>obs.observe(x));
const msg="Happy Birthday, Nehaaa! I hope today reminds you just how special you are. Talking to you has quietly become one of my favourite little parts of the day, and I am genuinely glad our paths crossed. So instead of sending you a normal birthday text, I wanted to make you a tiny corner of the internet that is just for you. I hope this year brings you endless reasons to smile, beautiful memories, and all the happiness you deserve. Keep smiling, keep being you, and have the sweetest birthday. ♡";let i=0,started=false;const typed=document.querySelector('#typed');new IntersectionObserver(es=>{if(es[0].isIntersecting&&!started){started=true;let t=setInterval(()=>{typed.textContent+=msg[i++];if(i>=msg.length)clearInterval(t)},23)}},{threshold:.35}).observe(typed);
document.querySelectorAll('.grid img').forEach(im=>im.onclick=()=>{document.querySelector('#big').src=im.src;document.querySelector('#lightbox').classList.add('open')});document.querySelector('#close').onclick=()=>document.querySelector('#lightbox').classList.remove('open');document.querySelector('#lightbox').onclick=e=>{if(e.target.id==='lightbox')e.currentTarget.classList.remove('open')};
document.querySelector('#gift').onclick=()=>{document.querySelector('#final').classList.add('show');document.querySelector('#hint').textContent='you found it ♡';for(let n=0;n<45;n++){let s=document.createElement('span');s.textContent=['✦','♡','✧','♥'][Math.random()*4|0];s.style.cssText=`position:fixed;left:50%;top:65%;z-index:40;color:#f39ab9;font-size:${12+Math.random()*18}px;pointer-events:none`;document.body.append(s);s.animate([{transform:'translate(-50%,-50%)',opacity:0},{transform:`translate(${(Math.random()-.5)*innerWidth}px,${-(150+Math.random()*innerHeight*.7)}px) rotate(${Math.random()*700}deg)`,opacity:1}],{duration:1000+Math.random()*1000}).onfinish=()=>s.remove()}};
const c=document.querySelector('#stars'),x=c.getContext('2d');let dots=[];function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);dots=Array.from({length:55},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.3,v:Math.random()*.25+.05,a:Math.random()*.5+.15}))}function draw(){x.clearRect(0,0,innerWidth,innerHeight);dots.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=innerHeight;x.beginPath();x.arc(d.x,d.y,d.r,0,7);x.fillStyle=`rgba(245,190,220,${d.a})`;x.fill()});requestAnimationFrame(draw)}size();addEventListener('resize',size);draw();
let audio=false;
const bgMusic=document.querySelector('#bgMusic');
bgMusic.addEventListener('error',()=>{ if(audio){ audio=false; musicBtn.textContent='♪'; alert('Add your audio file as assets/music/I_Think_They_Call_This_Love_cover.mp3 first.'); }});
musicBtn.onclick=async()=>{
  audio=!audio;
  musicBtn.textContent=audio?'♫':'♪';
  if(audio){ try{await bgMusic.play();}catch(e){audio=false;musicBtn.textContent='♪';alert('Add your audio file as assets/music/I_Think_They_Call_This_Love_cover.mp3 first.');} }
  else bgMusic.pause();
};
